### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' and failed request with vision model

### ISSUE THREAD

**Issue by HysMX** [arcee-ai/fastmlx#42]
I was trying to use mlx-community/Llama-3.2-11B-Vision-Instruct-8bit with an image based on the example

```js
{
    "model": "mlx-community/Llama-3.2-11B-Vision-Instruct-8bit",
    "image": "http://images.cocodataset.org/val2017/000000039769.jpg",
    "messages": [{"role": "user", "content": "What are these"}],
    "max_tokens": 100,
    "stream": false
}
```

But in the terminal I was getting the error traceback
```
INFO:     127.0.0.1:57916 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/fastmlx/fastmlx.py", line 140, in chat_completion
    prompt = apply_vlm_chat_template(processor, config, chat_messages)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarcastro/miniforge3/lib/python3.12/site-packages/mlx_vlm/prompt_utils.py", line 142, in apply_chat_template
    if p.get("role") in ["system", "assistant"]: 
       ^^^^^
AttributeError: 'str' object has no attribute 'get'
```

Pasted the error into cursor and I was able to fix it on the prompt_utils.py inside the mlx_vlm package 
![Image](https://github.com/user-attachments/assets/dcda950f-8831-4091-bb8e-e54ea67d9eec)

Cursor said:
The error occurs because the code is trying to call .get() on a string when processing prompts. Let's fix the logic in the apply_chat_template function to properly handle both string and dictionary prompts.

The main changes are:
Added proper type checking before accessing the role attribute using .get()
Restructured the prompt processing logic to handle three cases:
List of strings
List of message dictionaries
List of lists (nested prompts)
Added is_special_role check to properly handle system and assistant messages
Simplified the logic for determining if a message should include image tokens
This should fix the AttributeError by ensuring we only call .get() on dictionary objects, not strings.

and voila it works now

![Image](https://github.com/user-attachments/assets/8e2bc5a5-0e52-4e6f-a3de-368d7ac12b7c)

I know this is not a proper fix and might require to address it with the maintainer of that other package but for me it works now, I hope you guys can reproduce it!

**Comment by Blaizzy** [comment]
Hey @HysMX 

FastMLX is due for refactoring, a lot has changed in mlx-vlm and mlx-lm. I will get to it soon.

Could you share a reproducible example?

**Comment by Blaizzy** [comment]
I'm the maintainer of mlx-vlm and core contributor to mlx-lm.

**Comment by Blaizzy** [comment]
Which version of mlx-vlm are you using?

**Comment by HysMX** [comment]
Sorry for the late response, I'm using the latest 0.2.1
